### ISSUE TITLE
Deal Button Image 

### ISSUE THREAD

**Issue by Lucas-Campos-Davis** [cs361fall2017/team27#11]
Make the Deal Button an image of a card back

**Comment by terri-hewitt** [comment]
It's very difficult to see that what the deal button says. Maybe try using this code to make an image into a button: <img src="path_to_your_image" onclick="your_function();" />

For the image source, see if this image will work: https://drive.google.com/file/d/0B0iNUFPfmkD2VlpZTmFfdTRKRDg/view?usp=sharing 

I used Paint to modify the cardback image so it says "Deal". You can then use CSS to resize the image so that it is equal to the width of one of the columns.

**Comment by terri-hewitt** [comment]
I had to leave out the HTML tags on img because GitHub was parsing it as HTML, haha.

**Comment by Lucas-Campos-Davis** [comment]
Thanks!, I'll have this changed shortly
